language: python
python:
  - "3.6"
  - "3.8"
  - "3.9"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls

# command to run tests
script:
  - coverage run --source=flatstar/ -m pytest tests/
  - coveralls